### ISSUE TITLE
`Error: Parser cannot parse input: expected a value`

### ISSUE THREAD

**Issue by josephmturner** [RangerMauve/hyper-sdk-rpc#4]
Sending any request to the server gives `Error: Parser cannot parse input: expected a value`.

For example the following request

```
Content-Length: 66

{"jsonrpc":"2.0","id":1,"method":"sdk. foo","params":{"bar":"baz"}}
```

gives the following error:

```
Error: Parser cannot parse input: expected a value
    at Parser._processBuffer (/home/joseph/.local/src/hyper-sdk-rpc/node_modules/stream-json/Parser.js:111:64)
    at Parser._transformBuffer (/home/joseph/.local/src/hyper-sdk-rpc/node_modules/stream-json/utils/Utf8Stream.js:24:10)
    at Parser._transform (/home/joseph/.local/src/hyper-sdk-rpc/node_modules/stream-json/utils/Utf8Stream.js:19:10)
    at Transform._write (node:internal/streams/transform:175:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Chain._write (/home/joseph/.local/src/hyper-sdk-rpc/node_modules/stream-chain/index.js:152:18)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
```

As far as we can tell, the JSON requests are not being parsed correctly. For example, in `ServerConnection.process()`, a `console.log` statement just inside `for await (const { value: response } of parser) { ...` block does not run before the error is thrown.

**Comment by RangerMauve** [comment]
Is the line "content-length 66" part of the data sent down the wire?

Is this part of the json-rpc spec that I'm not aware of? This would cause parser errors since we're expecting a stream with just json data.

**Comment by josephmturner** [comment]
There's <https://www.jsonrpc.org/historical/json-rpc-over-http.html#http-header>, which specifies that JSON-RPC over HTTP must accept those headers.  But... we're not sending requests over HTTP, so I think that this is probably an issue on the Emacs end.

Thank you!!

**Comment by josephmturner** [comment]
When I remove the HTTP header,  that error goes away.
